name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pytest coverage
      - name: Run tests with coverage
        run: |
          coverage run -m pytest
      - name: Generate coverage report
        run: |
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          token: d942221f-6f8f-412a-a646-6986084cd63a
          slug: amirhossein226/yhttp-app-sample
          name: codecov-python
